# Generated by Django 5.2.5 on 2025-10-02 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0001_initial'),
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_related_label', to='label.label')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_related_status', to='statuses.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_related_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
